#!/bin/bash

clear
echo -e "\033[1;36mPackSSH es un script para crear, eliminar, definir limite de usuários, etc. PackSSH fue creado por Mr.SSH.\033[0m"
echo -e "\033[1;31mPara continuar con la instalacion presione ENTER, para cancelar CTRL + C\033[0m"
read  #enter
echo -e "\033[1;36m         Iniciando instalacion de PackSSH.\033[0m"
sleep 2
rm install
rm install.1
clear
apt-get update -y 
apt-get install wget sudo -y
clear
wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/InstallerPackSSH && bash InstallerPackSSH
clear
echo -e \033[1;36m Usar el comando \033[1;36mPackSSH \033[1;36mpara tener acesso a las opciones.\033[0m
sleep 3
203