#!/bin/bash

clear
echo -e "\033[1;36mPackSSH é um script para criar, apagar, definir limite de usuários, etc. PackSSH foi criado por Mr.SSH.\033[0m"
echo -e "\033[1;31mPara prosseguir com a instalação pressione ENTER, para cancelar CTRL + C\033[0m"
read  #enter
echo -e "\033[1;36m         Iniciando instalação do PackSSH.\033[0m"
sleep 2
rm install
rm install.1
clear
apt-get update -y 
apt-get install wget sudo -y
clear
wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/InstallerPackSSH && bash InstallerPackSSH
clear
echo -e \033[1;36m User o comando \033[1;36mPackSSH \033[1;36mpara ter acesso às opções.\033[0m
sleep 3
203