#!/bin/bash

clear
echo -e "\033[1;36mBadManager es un script para crear usuarios, eliminar usuários, etc. Su principal diferencia es el uso de varios lenguajes de programacion para su creacion.\033[0m"
echo -e "\033[1;31mPara continuar con la instalacion presiona ENTER, para cancelar CTRL + C\033[0m"
read  #enter
rm install
rm install.1
clear
echo -e "\033[1;36m       Iniciando instalacion de BadManager.\033[0m"
sleep 3
apt-get update -y 
apt-get install wget sudo -y
clear
sudo apt-get install wget -y && wget -q https://raw.githubusercontent.com/BadGuy552/BadManager/master/instalar.sh && sudo bash instalar.sh && rm instalar.sh
sleep 5
203