#!/bin/bash


clear
if [ -f /bin/badvpn ]
  then
  echo -e "\033[1;35mO BadVPN ya está instalado.\033[0m" 
  echo -e "\033[1;35mA Reinstalacion no recomendada.\033[0m" 
    echo ""
    echo -n -e "\033[1;31mInstalar BadVPN nuevamente(S/n)?\033[0m"
   
    read resp
    if [ "$resp" == "S" ]; then
     echo -e "\033[1;31mInstalando, espera....\033[0m" 
     sleep 2
     wget https://raw.githubusercontent.com/RicKbrL/badvpn/master/easyinstall && bash easyinstall
     clear
     echo -e "\033[1;36mInstalacion Terminada :).\033[0m"
     sleep 1
     echo -e ""
     echo -n -e "\033[1;31mDeseja iniciar o BADVPN?(S/n):\033[0m"
     elif [ "$resp" == "n" ]; then
        echo "" 
        echo -e "\033[1;36m              Instalacion Terminada.\033[0m"
        sleep 1
        2
   fi
  true
  else
    echo -e "\033[1;36mBadVPN es un programa que abre puertos UDP en el servidor que permiten el servicio VOIP como la conexion con WhatsApp.\033[0m"
    sleep 2
    echo " "
    echo -e "\033[1;31mInstalando, espera....\033[0m"
    sleep 2
    wget https://raw.githubusercontent.com/RicKbrL/badvpn/master/easyinstall && bash easyinstall
    clear
    echo -e "\033[1;36mInstalacion terminada :).\033[0m"
    sleep 1
    echo -e ""
    echo -n -e "\033[1;31mDesea iniciar o BADVPN?(S/n):\033[0m"
    read resp
    if [ "$resp" == "S" ]; then
       badvpn start
       sleep 2
       2
    elif [ "$resp" == "n" ]; then
      echo -e "\033[1;37m          Cuando desees iniciar BadVPN utiliza el comando \033[1;31m2042.\033[0m"
      sleep 1
     2
   fi
fi


