#!/bin/bash

clear
echo -e "\033[1;36mO Bad UDP será instalado, Bad UDP é um programa que libera portas UDP no servidor e assim permitindo serviço VOIP como ligação no WhatsApp, a instalação começará em 15 segundos, \033[1;35mpara cancelar pressione CTRL + C.\033[0m"
sleep 15
clear
echo -e "\033[1;31mInstalando, aguarde....\033[0m"
sleep 2
wget https://raw.githubusercontent.com/RicKbrL/badvpn/master/easyinstall && bash easyinstall
clear
echo -e "\033[1;36mInstalação Concluída :).\033[0m"
sleep 1
echo -e ""
echo -n -e "\033[1;31m Deseja iniciar o Bad UDP?(S/n):\033[0m"
read resp
if [ "$resp" == "S" ]; then
       badvpn start
       sleep 2
       2
elif [ "$resp" == "n" ]; then
    echo -e "\033[1;37m          Quando quiser iniciar o Bad UDP utilize o comando \033[1;31m2042.\033[0m"
    sleep 1
    2
fi