#!/bin/bash

if [ -f /bin/badvpn ]
  then
        echo -e "\033[1;31m        Iniciando...\033[0m" 
        echo ""
         badvpn start
       sleep 2
       echo ""
        echo -e "\033[1;36m  BadVPN iniciado.\033[0m"
       sleep 1
        2
  true
  else
    echo -e "\033[1;31mError! BadVPN no esta instalado.\033[0m"
    echo " "
    echo -n -e "\033[1;35mDeseas instalar BadVPN (S/n):\033[0m"
    
     read resp
      if [ "$resp" == "S" ]; then
        echo -e "\033[1;31mInstalando, espera....\033[0m"
        sleep 2
        wget https://raw.githubusercontent.com/RicKbrL/badvpn/master/easyinstall && bash easyinstall
        clear
        echo -e "\033[1;36mInstalacion Terminada :).\033[0m"
        sleep 1
        echo -e "\033[1;36mIniciando BadVPN.\033[0m"
        badvpn start
        clear
        echo -e "\033[1;36mBadVPN iniciado.\033[0m"
        sleep 2
        2
      elif [ "$resp" == "n" ]; then
        2
     fi
fi