#!/bin/bash

if [ -f /bin/badvpn ]
  then
  echo -e "\033[1;31mDeteniendo..\033[0m"
    sleep 2
    badvpn stop
    clear
    echo -e "\033[1;36mBadVPN detenido.\033[0m"
    sleep 2
    2
   true
   else
     echo -e "\033[1;31mError! BadVPN no esta instalado.\033[0m"
   sleep 3s
   2
fi