#!/bin/bash

clear
echo -e "\033[1;36mEscoja una de las opciones siguientes.\033[0m"
echo -e "\033[1;36m1 |OS
  \033[0;37m|Actualizar sistema operacional (Ubuntu ou Debian). 
\033[1;36m2 |Paquetes
  \033[0;37m|Actualizar lista de paquetes y todos los paquetes instalados.
\033[1;36m3 |Seguridad
  \033[0;37m|Instala actualizaciones de seguridad en sistemas Ubuntu e Debian.
\033[1;36m4 |Regresar
  \033[0;37m|regresar al menu anterior.\033[0m"
read -p "Opcion:" opcao

case $opcao in
 1)
  2061;;
 2) 
  2062;;
  3) 
  2063;;
  4)
  2;;
  *) 
  id > /dev/null 2> /dev/null
esac