#!/bin/bash

clear
echo -e "\033[1;36mTu SO será atualizado a la version mas reciente. \033[1;36mNo continues a menos que sepas lo que estas haciendo.\033[0m"
echo -e "\033[1;36mSerán mostrados textos en ingles. La actualizacion puede demorar mucho, Se paciente.\033[0m"
echo -e "\033[1;31mPara continuar presione ENTER, para cancelar CTRL + C \033[0m"
read  #enter
do-release-upgrade
clear
2