#!/bin/bash

clear
read -p "Escribe el nuevo hostname de la maquina: " hostname
hostname $hostname
echo -e "\033[1;36m Hostname actualizado, cierra esta sesion SSH y entre nuevamente.\033[0m"
sleep 3
2