#!/bin/bash

rm install
rm instalar.sh
rm easyinstall
rm conf
clear
echo -e "\033[1;36mEsto configurará plenamente su servidor, puede instalar un gestor, BadVPN y Squid, todas las opciones son opcionales.\033[1;31m Para continuar pressione ENTER para cancelar pressione CTRL + C.\033[0m"
read #enter
echo -e "\033[1;35mDevido a problemas de incompatibilidad no hay opcion para instalar PackSSH, para instalar use el comando \033[1;31m2033.\033[0m"
echo " "
if [ -f /bin/vpspack ]
  then
  echo -e "\033[1;31mVpsPack \033[1;36myá está instalado.\033[0m"
  true
  if [ -f /bin/PackSSH ]
  then
  echo -e "\033[1;31mPackSSH \033[1;36myá está instalado.\033[0m"
  true
  fi
  if [ -f /bin/CONFVPS ]
  then
  echo -e "\033[1;31mCONFVPS \033[1;36myá está instalado,  a instalação do mesmo não é necessária.\033[0m"
  true
  fi
  if [ -f /bin/iniciar ]
  then
  echo -e "\033[1;31mBadManager \033[1;36myá está instalado.\033[0m"
  true
  fi
  if [ -f /bin/ajuda ]
  then
  echo -e "\033[1;31mVPSManager \033[1;36myá está instalado.\033[0m"
  true
  fi
fi
echo " "
echo -e "\033[1;37mEscoje uno de los script de Administracion abajo.\033[0m" 
echo ""
echo -e "\033[1;36m1|VpsPack
 \033[0;37m|Instalar VpsPack. 
\033[1;36m2|CONFVPS
 \033[0;37m|Instalar CONFVS.
\033[1;36m3|BadManager
 \033[0;37m|Instalar BadManager.
\033[1;36m4|VPSManager
 \033[0;37m|Instalar VPSManager.
\033[1;36m5|Ninguna
 \033[0;37m|Omita este paso y no instale ninguna
\033[1;36m6|Regresar
 \033[0;37m|Volver al menu anterior.\033[0m"
read -p "Opcion:" opcao

case $opcao in
 1)
clear
echo -e "\033[1;36mVpsPack es un script de Administracion. VpsPack fue creado por Luiz. \033[0m"
sleep 3
rm install
rm install.1
apt-get update -y 
apt-get install wget sudo -y
clear
echo -e "\033[1;36m        Iniciando instalacion de VpsPack.\033[0m"
sleep 3
wget https://raw.githubusercontent.com/RicKbrL/VpsPack/master/install && bash install
echo -e "\033[1;31mPresiona enter para continuar.\033[0m"
read  #enter
clear
211c;;
 2) 
echo -e "\033[1;36mCONFVPS  es un script de Administracion, creado por Glemysson.\033[0m"
rm install
rm install.1
clear
apt-get update -y
apt-get install wget sudo -y
clear
echo -e "\033[1;36m         Iniciando instalacion de CONFVPS.\033[0m"
sleep 3
wget https://raw.githubusercontent.com/glemysson-Hacker/GlEmYsSoN/master/installer.sh
chmod +x installer.sh
bash installer.sh
echo -e "\033[1;31mPressione ENTER para terminar.\033[0m"
read #enter 
211c;;
 3)
echo -e "\033[1;36mBadManager  es un script de Administracion creado por BadGuy. su principal diferencia es el uso de varios lenguajes para su creacion.\033[0m"
clear
echo -e "\033[1;36m       Iniciando instalacion de BadManager.\033[0m"
sleep 3
apt-get update -y 
apt-get install wget sudo -y
clear
sudo apt-get install wget -y && wget -q https://raw.githubusercontent.com/BadGuy552/BadManager/master/instalar.sh && sudo bash instalar.sh && rm instalar.sh
echo -e "\033[1;31mPressione ENTER para terminar.\033[0m"
read #enter
211c;;
 4)
echo -e "\033[1;36mVPSManager es un script de Administracion por Phreaker56.\033[0m"
clear
echo -e "\033[1;36m       Iniciando instalacion VPSManager.\033[0m"
sleep 3
apt-get update -y 
apt-get install wget sudo -y
clear
wget http://phreaker56.wap.sh/vpsmanagersetup.sh
chmod +x vpsmanagersetup.sh
./vpsmanagersetup.sh
echo ""
echo -e "\033[1;31mPresiona ENTER para terminar.\033[0m"
read #enter 
211c
;;
 5)
   211c;;
  6)
   2;;
 *)
  id > /dev/null 2> /dev/null
 esac