#!/bin/bash

clear
if [ -f /bin/badvpn ]
  then
      echo -e "\033[1;31mBadVPN \033[1;36mya esta instalado en el servidor, en caso que desee reinstalarlo escoja la opcion 4 del menu anterior o use el comando \033[1;31m204.\033[0m"
      echo -e "\033[1;35mPresiona enter para continuar.\033[0m"
      read  #enter
      true
      else
      echo -e "\033[1;36mBadVPN es un programa que libera puertos UDP en el servidor y permitiendo el servicio VOIP ligado a WhatsApp, y juegos online.\033[0m"
      echo " "
      echo -n -e "\033[1;31mDesea instalar BadVPN? (S/n):\033[0m"

     read resp
     if [ "$resp" == "S" ]; then
       sleep 1
       echo -e "\033[1;31mInstalando, espera...\033[0m"
       sleep 2
       wget https://raw.githubusercontent.com/RicKbrL/badvpn/master/easyinstall && bash easyinstall
       clear
       echo -e "\033[1;36mInstalacion de BadVPN Terminada :).\033[0m" 
       sleep 5
       20342
       elif [ "$resp" == "n" ]; then
       clear
       echo -e "\033[1;31m              Instalacion de BadVPN cancelada.\033[0m"
       fi
fi
rm conf
clear
if [ -d /etc/squid ] || [ -d /etc/squid3 ]
  then
  echo -e "\033[1;31mSquid ya esta instalado. \033[1;36m Si quieres instalar Squid nuevamenta usa la opcion 2 del menu anterioro usa el comando \033[1;31m202.\033[0m"
  echo -e "\033[1;35mPresiona enter para continuar.\033[0m"
  read #enter
  2
  true
  else
   echo -e "\033[1;36mO Squid es obligatorio para conectarse al servidor utilizando SSH.\033[0m" 
   echo -n -e "\033[1;35mDeseas instalar e configurar o Squid ?(S/n):\033[0m"
   read resp
   if [ "$resp" == "S" ]; then
   echo " "
   echo -e "\033[1;31m         Instalando y configurando Squid, Espera...\033[0m"
   sleep 5
   wget https://raw.githubusercontent.com/Devimla/Squid/master/conf && bash conf
   echo " "
   echo -e "\033[1;31m                   Configuracion del sistema terminada.\033[0m"
   echo -e "\033[1;36m                   Gracias por escojer AdmScript.\033[0m"
   sleep 3
   2
   elif [ "$resp" == "n" ]; then
   clear
   echo -e "\033[1;36mTen en cuenta que sin Squid instalado sus archivos no Conectaran.\033[0m"
   sleep 3
   echo -e "\033[1;31m        Instalacion de Squid cancelada.\033[0m"
   sleep 3
   2
  fi
fi