#!/bin/bash

function tentaracelerar(){
clear
echo -e "\033[1;36mla velocidad del servidor puede o no ser aumentada, tenga en mente que el aumento de velocidad no esta 100% garantizado.\033[0m"
echo " "
echo -e "\033[1;36mEn caso de que ocurra algun error despues de usar esta opcion revierte los cambios usando la opcion revertir en el menu anterior.\033[0m"
echo " "
echo -n -e "\033[1;31mDeseas continuar? (S/n):\033[0m"
read resp
if [ "$resp" == "S" ]; then
    echo "" 
    echo -e "\033[1;31mIntentando acelerar el servidor, espera...\033[0m"
    sleep 3
    echo "Compression yes" >> /etc/ssh/sshd_config
    service sshd restart
    clear
    echo -e "\033[1;36mIntento de aceleracion Terminado.\033[0m" 
    sleep 4
    2
elif [ "$resp" == "n" ]; then
    echo "" 
    echo -e "\033[1;31mIntento de aceleracion Cancelado.\033[0m"
    sleep 3
    2
fi
}
function revertercrompressao(){
echo -e "\033[1;36mAguarde...\033[0m"
sed -i '/^Compression yes$/d' /etc/ssh/sshd_config
service sshd restart
sleep 2
echo -e "\033[1;36mTerminado.\033[0m"
sleep 2
2
}
clear
echo -e "\033[1;31mPara salir precione Ctrl + C\033
\033[1;36m 1|Acelerar
 \033[0;37m |Intentar acelerar el servidor.
\033[1;36m 2|Revertir
 \033[0;37m |Revertir intento de aceleracion
\033[1;36m 3|Regresar
 \033[0;37m |Regresar al menu anterior.\033[0m"
read -p "Opcion:" opcao

case $opcao in
 1)
  tentaracelerar;;
 2) 
  revertercrompressao;;
 3)
  2;;
  *) 
  id > /dev/null 2> /dev/null
esac

