#!/bin/bash

clear
echo -e "\033[1;31mATENCION!!!\033[0m \033[1;35mSi continúa todos los usuarios (excepto el sistema y Root) del servidor será desconectado y borrado, \033[1;31mESTA ACCION NO PODRA SER REVERTIDA, PROSIGE CON CAUTELA.\033[0m" 
echo -n -e "\033[1;36m DeseaS continuar?(SI/n):\033[0m"

read resp
if [ "$resp" == "SI" ]; then
    echo -e "\033[1;31m Espera, eliminando usuários.....\033[0m"
    for user in $(grep -v nobody /etc/passwd |awk -F : '$3 > 900 {print $1}'); do kill $(ps -u $user |awk '{print $1}'); userdel $user; done
    sleep 5
    clear 
    echo -e "\033[1;36m Todos los usuários fueron eliminados correctamente :).\033[0m"
elif [ "$resp" == "n" ]; then
    clear 
    echo -e "\033[1;36m              Eliminacion Cancelada :)\033[0m"
fi
