#!/bin/bash

clear
echo -e "\033[1;31mATENCION: \033[1;36mNo añada a el grupo sudo usuários que son utilizados para tunel SSH (ehi, ePro, ktc, etc). Caso contrário estaras dejando tu servidor vulnerable.\033[0m"
echo -e "\033[1;35mPresiona enter para continuar.\033[0m" 
read #enter
clear
echo -e "\033[1;35mEscribe el nombre de usuario\033[0m"
read -p ": " usuario
sleep 3
sudo gpasswd -a $usuario sudo
clear
echo -e "\033[1;31m$usuario \033[1;36mfue agregado a grupo sudo.\033[0m"
sleep 2
2