#!/bin/bash

echo -e " \033[1;36m                 Adm script\033[0m"
echo -e " \033[1;36m               ==========\033[0m"
echo " "
echo -e "\033[1;30m||\033[1;36mCriado por: \033[4;35mDevim\033[0m"
echo -e "\033[1;30m||\033[0m"
echo -e "\033[1;30m||\033[1;36mCriado em: \033[4;35m14/02/2017\033[0m"
echo -e "\033[1;30m||\033[0m"
echo -e "\033[1;30m||\033[1;36mVersão: \033[4;35m1.0\033[0m" 
echo -e "\033[1;30m||\033[0m"
echo -e "\033[1;30m||\033[1;36mDencrição: \033[4;35mComandos simples, úteis e que muitos não tem conhecimento, troca de senha, reiniciar sistema, etc, todos esses é muito mais nesse simples script. Script criado sem fins lucrativos\033[0;35m.\033[0m"
echo " "
