#!/bin/bash

roxo="\033[1;35m"
red="\033[1;31m"
azul="\033[1;36m"

clear
echo 
echo -e "\033[41m                         ATALHOS                       \033[0m"
echo " "
echo -e "\033[1;36mTodos as opções disponíveis no script podem ser acessadas por um número que a corresponde, no caso o número de origem seguida do número da opção no sub menu.\033[0m" 
echo ""
echo -e "\033[1;31mExemplo:\033[0m"
echo -e "\033[1;36mSupondo que queira alterar o hostname do servidor, o caminho lógico seria \033[1;31madm > 2 > 12\033[1;36m, onde o \033[1;31m2 \033[1;36mé a opção de \033[1;35mconfiguração e informações sobre o sistema desse servidor,\033[1;36m no menu principal e em seguida o número da opção que no caso é \033[1;31m12, \033[1;36mentão para trocar o hostname o comando direto seria \033[1;31m212.\033[0m"
echo ""
echo -e "\033[1;36mMas e se a sub opção for algum número de 1 a 9, supondo que queira limpar o cache e swap do servidor, o caminho seria \033[1;31madm > 2 > 1 \033[1;36mnesse caso se aplica um zero na frente do número de direção, no caso em frente do 2, e em seguida o número da opção, no caso o 1, então o comando para limpar o cache e swap é \033[1;31m201.\033[0m"