#!/bin/bash
cd

if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "No eres Root"
        echo "Su usuario no esta en el grupo sudo"
        echo -e "Para convertirse en root y ejecutar la instalación \033[1;31msudo su\033[0m"
        exit
        else
        clear
        echo -e "Es necesario ser root para poder instalar, para convertirse en root ejecute \033[1;31msu\033[0m y digite su contraseña"
        exit
        fi
fi

if [ -f /bin/adm ]
  then
  echo -e "\033[1;36mAdmScript ya está instalado, será necesaria una desinstalacion de la vercion actual para instalar nuevamente.\033[0m"
  echo " "
  echo -e "\033[1;31mDesea desinstalar el AdmScript instalado atualmente? (S/n)\033[0m"
  
  read resp
  if [ "$resp" == "S" ];then
      echo ""
      echo -e "\033[1;36mDesinstalando AdmScript, espere...\033[0m"
        rm /bin/adm
        rm /bin/1
        rm /bin/2
        rm /bin/3
        rm /bin/4
        rm /bin/101
        rm /bin/102
        rm /bin/103
        rm /bin/104
        rm /bin/201
        rm /bin/202
        rm /bin/203
        rm /bin/2031
        rm /bin/2032
        rm /bin/2033
        rm /bin/204
        rm /bin/2041
        rm /bin/2042
        rm /bin/2043
        rm /bin/205
        rm /bin/206
        rm /bin/207
        rm /bin/207.py
        rm /bin/208
        rm /bin/209
        rm /bin/210
        rm /bin/211
        rm /bin/212
        rm /bin/213
        rm /bin/214
        rm /bin/215
        rm /bin/216
        rm /bin/217
        rm /bin/218
   sleep 3
   rm /bin/5
   clear
   echo -e "\033[1;31m               Desinstalacion concluída.\033[0m"
   sleep 2
   echo -e "\033[1;36m         Iniciando instalacion, espere...\033[0m"
   sleep 3
   if yum
   then
   yum -y update
   yum -y install git
   git clone https://github.com/Devimla/AdmScript.git
   clear
   cd AdmScript
   rm -rf README.md
   rm -rf install
   for arqs in `ls`
   do
   rm /bin/$arqs 2>/dev/null
   mv $arqs /bin
   chmod +x /bin/$arqs
   done
   echo -e "\033[1;36mTerminado, execute el comando \033[1;31madm\033[1;36m como usuário root o usuario con permiso sudo.\033[0m"
   echo -e "\033[1;31mPresiona ENTER para terminar.\033[0m"
   read #enter
   adm
   else
   apt-get update
   apt-get install -y git
   git clone https://github.com/Devimla/AdmScript.git
   clear
   cd AdmScript
   rm -rf README.md
   rm -rf install
   for arqs in `ls`
   do
   rm /bin/$arqs 2>/dev/null
   mv $arqs /bin
   chmod +x /bin/$arqs
   done
   echo -e "\033[1;36mTerminado, execute el comando \033[1;31madm \033[1;36m como usuário root o usuario con permiso sudo.\033[0m"
   echo -e "\033[1;31mPressiona ENTER para terminar.\033[0m"
   read #enter
   adm
   fi
   elif [ $resp -eq "n" ];then
    echo -e "\033[1;31m              Desinstalacion cancelada.\033[0m"
    sleep 1
    adm
  fi
  true
  else
   echo -e "\033[1;36mAdmScript, script basado en VpsPack que tiene como objetivo ayudar, sin necesidad de aprender scripts o comandos.\033[0m"
   echo " "
   echo -e "\033[1;31mPara continuar pressione ENTER, para cancelar CTRL + C.\033[0m"
   read  #enter
   echo " "
   echo -e "\033[1;36m         Iniciando instalacion, espere...\033[0m"
   sleep 3
   if yum -y update
   then
   yum -y update
   yum -y install git
   git clone https://github.com/Devimla/AdmScript.git
   clear
   cd AdmScript
   rm -rf README.md
   rm -rf install
   for arqs in `ls`
   do
   rm /bin/$arqs 2>/dev/null
   mv $arqs /bin
   chmod +x /bin/$arqs
   done
   echo -e "\033[1;36mTerminado, execute el comando \033[1;31madm\033[1;36m como usuário root o usuario con permiso sudo.\033[0m"
   echo -e "\033[1;31mPressiona ENTER para terminar.\033[0m"
   read #enter
   adm
   else
   apt-get update
   apt-get install -y git
   git clone https://github.com/Devimla/AdmScript.git
   clear
   cd AdmScript
   rm -rf README.md
   rm -rf install
   for arqs in `ls`
   do
   rm /bin/$arqs 2>/dev/null
   mv $arqs /bin
   chmod +x /bin/$arqs
   done
   echo -e "\033[1;36mTerminado, execute el comando \033[1;31madm \033[1;36m como usuário root o usuário con permisos sudo.\033[0m"
   echo -e "\033[1;31mPressiona ENTER para terminar.\033[0m"
   read #enter
   adm
  fi
fi
cd
rm -rf install 2> /dev/null
rm -rf AdmScript 2> /dev/null
